module.exports = {
    srConfigAbout: (delay = 100) => ({
        // origin: 'right',
        // distance: '300px',
        duration: 500,
        delay,
        rotate: { x: 0, y: 0, z: 0 },
        opacity: 0,
        scale: 1,
        easing: 'cubic-bezier(.23,.89,.77,1.17)',
        mobile: true,
        reset: false,
        useDelay: 'always',
        viewFactor: 0,
        viewOffset: { top: 0, right: 0, bottom: 0, left: 0 },
    }),
    srConfigAboutText: (delay = 200) => ({
        // origin: 'left',
        // distance: '150px',
        duration: 1000,
        delay,
        rotate: { x: 0, y: 0, z: 0 },
        opacity: 0,
        scale: 1,
        easing: 'cubic-bezier(.23,.89,.77,1)',
        mobile: true,
        reset: false,
        useDelay: 'always',
        viewFactor: 0,
        viewOffset: { top: 0, right: 0, bottom: 0, left: 0 },
    }),
    srConfigButton: (delay = 600) => ({
        duration: 700,
        delay,
        opacity: 0,
        scale: 1,
        easing: 'cubic-bezier(.23,.89,.77,1)',
        mobile: true,
        reset: false,
        useDelay: 'always',
        viewFactor: 0,
        viewOffset: { top: 0, right: 0, bottom: 0, left: 0 },
    }),

    srConfigTechs: (delay = 0) => ({
        // origin: 'left',
        // distance: '200px',
        duration: 800,
        delay,
        rotate: { x: 0, y: 0, z: 0 },
        opacity: 0,
        scale: 1.5,
        easing: 'cubic-bezier(.23,.89,.77,1)',
        mobile: true,
        reset: false,
        useDelay: 'always',
        viewFactor: 0,
        viewOffset: { top: 0, right: 0, bottom: 0, left: 0 },
    }),

    srConfigWork: (delay = 0) => ({
        // origin: 'right',
        // distance: '300px',
        duration: 500,
        delay,
        rotate: { x: 0, y: 0, z: 0 },
        opacity: 0,
        scale: 1,
        easing: 'cubic-bezier(.23,.89,.77,1.17)',
        mobile: true,
        reset: false,
        useDelay: 'always',
        viewFactor: 0,
        viewOffset: { top: 0, right: 0, bottom: 0, left: 0 },
    }),
    srConfigProject: (delay = 300) => ({
        // origin: 'bottom',
        // distance: '200px',
        duration: 500,
        delay,
        rotate: { x: 0, y: 0, z: 0 },
        opacity: 0,
        scale: 1,
        easing: 'cubic-bezier(.23,.89,.77,1)',
        mobile: true,
        reset: false,
        useDelay: 'always',
        viewFactor: 0,
        viewOffset: { top: 0, right: 0, bottom: 0, left: 0 },
    }),


    srConfigContact: (delay = 500) => ({
        // origin: 'right',
        // distance: '300px',
        duration: 500,
        delay,
        rotate: { x: 0, y: 0, z: 0 },
        opacity: 0,
        scale: 1,
        easing: 'cubic-bezier(.23,.89,.77,1.17)',
        mobile: true,
        reset: false,
        useDelay: 'always',
        viewFactor: 0,
        viewOffset: { top: 0, right: 0, bottom: 0, left: 0 },
    }),
    srConfigContactText: (delay = 700) => ({
        // origin: 'left',
        // distance: '150px',
        duration: 1000,
        delay,
        rotate: { x: 0, y: 0, z: 0 },
        opacity: 0,
        scale: 1,
        easing: 'cubic-bezier(.23,.89,.77,1)',
        mobile: true,
        reset: false,
        useDelay: 'always',
        viewFactor: 0,
        viewOffset: { top: 0, right: 0, bottom: 0, left: 0 },
    }),
    srConfigContactEmail: (delay = 1000) => ({
        // origin: 'bottom',
        // distance: '50px',
        duration: 1000,
        delay,
        rotate: { x: 0, y: 0, z: 0 },
        opacity: 0,
        scale: 1,
        easing: 'cubic-bezier(.23,.89,.77,1.0)',
        mobile: true,
        reset: false,
        useDelay: 'always',
        viewFactor: 0,
        viewOffset: { top: 0, right: 0, bottom: 0, left: 0 },
    }),

    srConfigSocials: (delay = 0) => ({
        duration: 3000,
        delay,
        rotate: { x: 0, y: 0, z: 0 },
        opacity: 0,
        scale: 1,
        easing: 'cubic-bezier(.23,.89,.77,1)',
        mobile: true,
        reset: false,
        useDelay: 'always',
        viewFactor: 0,
        viewOffset: { top: 0, right: 0, bottom: 0, left: 0 },
    }),
};
